# Generated by Django 4.1 on 2022-08-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='gander',
            new_name='gender',
        ),
    ]
